FROM nginx:1.13-alpine

WORKDIR /var/www/Minds

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/nginx.conf
COPY dev-ssr.conf /etc/nginx/conf.d/dev.conf
COPY nginx_entrypoint_dev_ssr.sh /nginx_entrypoint_dev_ssr.sh

ENTRYPOINT /nginx_entrypoint_dev_ssr.sh
